### ISSUE TITLE
Failed resolution of: Landroidx/paging/DifferCallback

### ISSUE THREAD

**Issue by FunkyMuse** [cashapp/multiplatform-paging#245]
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.paging.DifferCallback"
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/paging/DifferCallback;
at androidx.paging.compose.LazyPagingItemsKt.collectAsLazyPagingItems(LazyPagingItems.kt:233)
at app.cash.paging.compose.LazyPagingItemsKt.collectAsLazyPagingItems(LazyPagingItems.kt:55)
```

```toml
[versions]
#paging
androidx-paging = "3.3.0-beta01"
cashapp-paging = "3.3.0-alpha02-0.5.1"

[libraries]
#paging
paging-runtime = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
paging-compose = { module = "app.cash.paging:paging-compose-common", version.ref = "cashapp-paging" }
```

The latest known compatible version is with `androidx-paging = "3.3.0-alpha02"`

**Comment by JakeWharton** [comment]
Note that this project is currently unmaintained, so there won't be any updates in the near term. I will still gladly review PRs, however.

**Comment by lmiskovic** [comment]
@FunkyMuse Have you managed to get around this? Having the same issue

**Comment by philipkraeutl** [comment]
any updates on this?

**Comment by labmember003** [comment]
any updatesss?

**Comment by MrMilkot** [comment]
Are there any ways to fix this?

**Comment by sproctor** [comment]
If you're only targeting platforms supported by AndroidX Paging, you can migrate to that. That seems to be the only way forward currently.

**Comment by vldi01** [comment]
@FunkyMuse You can try adding the "androidx.paging:paging-compose" dependency to the Android target 🤷. It fixed the issue on the Android side for me, but I haven't tried it on other targets yet.
Update: It doesn't fix the issue for IOS.

I guess there is a correlation with adding room dependency, as it was working for me until I added room (to different module tho)

**Comment by vldi01** [comment]
I was able to get around by implementing LazyPagingItems and extension fun from here

https://github.com/chrisbanes/tivi/blob/main/thirdparty/androidx/paging/compose/src/commonMain/kotlin/LazyPagingItems.kt

**Comment by bpappin** [comment]
Ahh, came here to drop that bug, but if its not maintained, then I don't see the point.

**Comment by GreatTusk** [comment]
> I was able to get around by implementing LazyPagingItems and extension fun from here
> 
> https://github.com/chrisbanes/tivi/blob/main/thirdparty/androidx/paging/compose/src/commonMain/kotlin/LazyPagingItems.kt

I can confirm that this approach works. In short, it involves copying the implementation of `androidx.paging.compose` for Android while providing actual implementations of `getPagingPlaceholderKey(index: Int): Any`—which is used for generating placeholder keys if a key factory isn't provided—for the JVM and iOS. Instead of writing/reading the index into a Parcelable like on Android, both implementations simply return the index

**Comment by vunder** [comment]
I faced the same error. After updating android paging library version and checking package name everything was working

```ini
[versions]
androidx-paging = "3.3.6"
multiplatform-paging = "3.3.0-alpha02-0.5.1"

[libraries]
paging-multiplatform-common = { module = "app.cash.paging:paging-common", version.ref = "multiplatform-paging" }
paging-multiplatform-compose-common = { module = "app.cash.paging:paging-compose-common", version.ref = "multiplatform-paging" }
paging-android = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
paging-uikit = { module = "app.cash.paging:paging-runtime-uikit", version.ref = "multiplatform-paging" }
```
```gradle
        commonMain.dependencies {
            implementation(libs.paging.multiplatform.common)
            implementation(libs.paging.multiplatform.compose.common)
        }
        androidMain.dependencies {
            implementation(libs.paging.android)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
            implementation(libs.paging.uikit)
        }
```

**Comment by phucynwa** [comment]
> I faced the same error. After updating android paging library version and checking package name everything was working
> 
> [versions]
> androidx-paging = "3.3.6"
> multiplatform-paging = "3.3.0-alpha02-0.5.1"
> 
> [libraries]
> paging-multiplatform-common = { module = "app.cash.paging:paging-common", version.ref = "multiplatform-paging" }
> paging-multiplatform-compose-common = { module = "app.cash.paging:paging-compose-common", version.ref = "multiplatform-paging" }
> paging-android = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
> paging-uikit = { module = "app.cash.paging:paging-runtime-uikit", version.ref = "multiplatform-paging" }
>         commonMain.dependencies {
>             implementation(libs.paging.multiplatform.common)
>             implementation(libs.paging.multiplatform.compose.common)
>         }
>         androidMain.dependencies {
>             implementation(libs.paging.android)
>         }
>         iosMain.dependencies {
>             implementation(libs.ktor.client.darwin)
>             implementation(libs.paging.uikit)
>         }

@vunder Have you tried on desktopJvm target ?
Related https://github.com/cashapp/multiplatform-paging/issues/377

**Comment by vunder** [comment]
Update on my case
I was facing this error with iOS platform. That was resolved with the [code snippet](https://github.com/cashapp/multiplatform-paging/issues/245#issuecomment-2764709440)
But when I started testing desktop - faced the same issue with `Didn't find class "androidx.paging.DifferCallback"`

Thanks to this I was able to run desktop too
> I was able to get around by implementing LazyPagingItems and extension fun from here
> 
> https://github.com/chrisbanes/tivi/blob/main/thirdparty/androidx/paging/compose/src/commonMain/kotlin/LazyPagingItems.kt

**Comment by vunder** [comment]
Unfortunately, workaround does not work for me fully. It fixed the issue on desktop, but breaking iOS compilation:
> error: java.lang.IllegalStateException: IrPropertySymbolImpl is already bound. Signature: androidx.paging/DEBUG|{}DEBUG[0]. Owner: PROPERTY name:DEBUG visibility:public modality:FINAL [const,val]

**Comment by LukasVykuka** [comment]
> Unfortunately, workaround does not work for me fully. It fixed the issue on desktop, but breaking iOS compilation:
> 
> > error: java.lang.IllegalStateException: IrPropertySymbolImpl is already bound. Signature: androidx.paging/DEBUG|{}DEBUG[0]. Owner: PROPERTY name:DEBUG visibility:public modality:FINAL [const,val]

Look at output of compilation error, maybe there is mention about workaround to put `kotlin.native.cacheKind=none` to `gradle.properties`.

**Comment by GreatTusk** [comment]
> Unfortunately, workaround does not work for me fully. It fixed the issue on desktop, but breaking iOS compilation:
> 
> > error: java.lang.IllegalStateException: IrPropertySymbolImpl is already bound. Signature: androidx.paging/DEBUG|{}DEBUG[0]. Owner: PROPERTY name:DEBUG visibility:public modality:FINAL [const,val]

Have you tried removing implementation(libs.paging.uikit)?

I don't have a mac to test it, but 

> I was able to get around by implementing LazyPagingItems and extension fun from here
> 
> https://github.com/chrisbanes/tivi/blob/main/thirdparty/androidx/paging/compose/src/commonMain/kotlin/LazyPagingItems.kt

copying these files _should_ be enough to get compose paging working for Android, JVM and iOS. I've only tested Android and JVM though.

**Comment by vunder** [comment]
> Look at output of compilation error, maybe there is mention about workaround to put kotlin.native.cacheKind=none to gradle.properties.

I already have this option. But disabling that gave me another error

```
error: Compilation failed: IrClassSymbolImpl is already bound. Signature: androidx.paging/ViewportHint|null[0]. Owner: CLASS CLASS name:ViewportHint modality:SEALED visibility:internal superTypes:[kotlin.Any]

 * Source files: 
 * Compiler version: 2.1.20
 * Output kind: FRAMEWORK

error: java.lang.IllegalStateException: IrClassSymbolImpl is already bound. Signature: androidx.paging/ViewportHint|null[0]. Owner: CLASS CLASS name:ViewportHint modality:SEALED visibility:internal superTypes:[kotlin.Any]
```


> Have you tried removing implementation(libs.paging.uikit)?

Did not help. Same error with or without this dependency
